### ISSUE TITLE
Imagenet finetuing doesn't work when set to "No" [BUG]

### ISSUE THREAD

**Issue by FerrariMatteo** [Malga-Vision/VisionTool#10]
I have encountered a problem regarding the "imagenet finetuing" option. The toolbox works fine as long as it is set to "Yes" but throws `ValueError: The weights argument should be either 'None' (random initialization), 'imagenet' (pre-training on ImageNet), or the path to the weights file to be loaded` when set to "No".

**Comment by VitoPaoloPastore** [comment]
Hi! thanks for reporting this issue. We fixed the bug and uploaded a new version of the toolbox!
