### ISSUE TITLE
Model Learning Issue

### ISSUE THREAD

**Issue by shivanthika** [Malga-Vision/VisionTool#2]
Hi,
I have used VisionTool to extract features from [MoCA dataset](https://github.com/nicolettanoceti/CookingDataset) which contain cooking actions. It seems that model train only with the first video (action) because when predicting, model gives perfect results on first video but poor precision on other video files.

**Comment by VitoPaoloPastore** [comment]
Hi,
thanks for reporting it. the bug has been solved, and the architectures_segmentation_multiple_videos.py has been consequently modified. 
Closing the issue.
