### ISSUE TITLE
Prediction fails when annotating 5 joints on the MoCa dataset

### ISSUE THREAD

**Issue by SofiaBagnato** [Malga-Vision/VisionTool#4]
Hi! When using as training set the [MoCa dataset](https://github.com/nicolettanoceti/CookingDataset), the trained model predicts joint locations at random points when annotating five joints (elbow, wrist, palm, index and little finger) per video. OS used is windows 10, with python version 3.8.

**Comment by VitoPaoloPastore** [comment]
Hi, we implemented a new class imbalance computation scheme that solved that issue!
thanks for using VisionTool!
